let movies = [
    {name: "The Terminator", rate: 8.0, image: "000.jpg"},
    {name: "Die Hard", rate: 8.2, image: "001.jpg"},
    {name: "Seven", rate: 8.6, image: "002.jpg"},
    {name: "Harry Potter and the Sorcerer's Stone", rate: 7.5, image: "003.jpg"},
    {name: "Gattaca", rate: 7.8, image: "004.jpg"},
    {name: "Looper", rate: 7.4, image: "005.jpg"},
    {name: "Pulp Fiction", rate: 8.9, image: "006.jpg"},
    {name: "The Shawshank Redemption", rate: 9.3, image: "007.jpg"},
    {name: "Meet the Fockers", rate: 6.3, image: "008.jpg"},
    {name: "Meet the Parents", rate: 7.0, image: "009.jpg"},
    {name: "A Pure Formality", rate: 7.8, image: "010.jpg"},
    {name: "The Aviator", rate: 7.5, image: "011.jpg"},
    {name: "The Italian Job", rate: 7.0, image: "012.jpg"},
    {name: "The Martian", rate: 8.0, image: "013.jpg"},
    {name: "Once Upon a Time in America", rate: 8.4, image: "014.jpg"},
    {name: "Back to the Future", rate: 8.5, image: "015.jpg"},
    {name: "Unforgiven", rate: 8.2, image: "016.jpg"},
    {name: "Minority Report", rate: 7.7, image: "017.jpg"},
    {name: "The Grand Budapest Hotel", rate: 8.1, image: "018.jpg"},
    {name: "The Game", rate: 7.8, image: "019.jpg"},
    {name: "Constantine", rate: 6.9, image: "020.jpg"},
    {name: "American Pie", rate: 7.0, image: "021.jpg"},
    {name: "Four Rooms", rate: 6.7, image: "022.jpg"},
    {name: "Reservoir Dogs", rate: 8.3, image: "023.jpg"},
    {name: "Groundhog Day", rate: 8.0, image: "024.jpg"},
    {name: "The Rundown", rate: 6.7, image: "025.jpg"},
    {name: "Lord of War", rate: 7.6, image: "026.jpg"},
    {name: "Kill Bill: Vol. 1", rate: 8.1, image: "027.jpg"},
    {name: "The Intouchables", rate: 8.6, image: "028.jpg"},
    {name: "Snatch", rate: 8.3, image: "029.jpg"},
    {name: "Now You See Me", rate: 7.3, image: "030.jpg"},
    {name: "Tucker and Dale vs Evil", rate: 7.6, image: "031.jpg"},
    {name: "The Ninth Gate", rate: 6.7, image: "032.jpg"},
    {name: "The Bourne Identity", rate: 7.9, image: "033.jpg"},
    {name: "The Bourne Supremacy", rate: 7.8, image: "034.jpg"},
    {name: "The Bourne Ultimatum", rate: 8.1, image: "035.jpg"},
    {name: "The Recruit", rate: 6.6, image: "036.jpg"},
    {name: "Phone Booth", rate: 7.1, image: "037.jpg"},
    {name: "Lucky Number Slevin", rate: 7.8, image: "038.jpg"},
    {name: "Mallrats", rate: 7.2, image: "039.jpg"},
    {name: "Casino Royale", rate: 8.0, image: "040.jpg"},
    {name: "Ocean's Eleven", rate: 7.8, image: "041.jpg"},
    {name: "The Straight Story", rate: 8.0, image: "042.jpg"},
    {name: "The Da Vinci Code", rate: 6.6, image: "043.jpg"},
    {name: "Forrest Gump", rate: 8.8, image: "044.jpg"},
    {name: "Scent of a Woman", rate: 8.0, image: "045.jpg"},
    {name: "The Departed", rate: 8.5, image: "046.jpg"},
    {name: "A Beautiful Mind", rate: 8.2, image: "047.jpg"},
    {name: "Inside Man", rate: 7.6, image: "048.jpg"},
    {name: "Donnie Brasco", rate: 7.8, image: "049.jpg"},
    {name: "The Dark Knight", rate: 9.0, image: "050.jpg"},
    {name: "Seven Psychopaths", rate: 7.2, image: "051.jpg"},
    {name: "Serenity", rate: 7.9, image: "052.jpg"},
    {name: "Hot Fuzz", rate: 7.9, image: "053.jpg"},
    {name: "Django Unchained", rate: 8.4, image: "054.jpg"},
    {name: "Warcraft: The Beginning", rate: 6.9, image: "055.jpg"},
    {name: "Rain Man", rate: 8.0, image: "056.jpg"},
    {name: "Goodfellas", rate: 8.7, image: "057.jpg"},
    {name: "Romancing the Stone", rate: 6.9, image: "058.jpg"},
    {name: "Shutter Island", rate: 8.1, image: "059.jpg"},
    {name: "Touching the Void", rate: 8.1, image: "060.jpg"},
    {name: "Pitch Black", rate: 7.1, image: "061.jpg"},
    {name: "Interstate 60: Episodes of the Road", rate: 7.7, image: "062.jpg"},
    {name: "Inception", rate: 8.8, image: "063.jpg"},
    {name: "Interview with the Vampire: The Vampire Chronicles", rate: 7.6, image: "064.jpg"},
    {name: "Lock, Stock and Two Smoking Barrels", rate: 8.2, image: "065.jpg"},
    {name: "The Revenant", rate: 8.0, image: "066.jpg"},
    {name: "Mission: Impossible", rate: 7.1, image: "067.jpg"},
    {name: "The Next Three Days", rate: 7.4, image: "068.jpg"},
    {name: "I Am Legend", rate: 7.2, image: "069.jpg"},
    {name: "Chungking Express", rate: 8.1, image: "070.jpg"},
    {name: "21 Jump Street", rate: 7.2, image: "071.jpg"},
    {name: "The Mask", rate: 6.9, image: "072.jpg"},
    {name: "The Sixth Sense", rate: 8.1, image: "073.jpg"},
    {name: "Black Cat, White Cat", rate: 8.1, image: "074.jpg"},
    {name: "Dead Poets Society", rate: 8.0, image: "075.jpg"},
    {name: "Deadpool", rate: 8.0, image: "076.jpg"},
    {name: "Dances with Wolves", rate: 8.0, image: "077.jpg"},
    {name: "Snowpiercer", rate: 7.0, image: "078.jpg"},
    {name: "Heat", rate: 8.2, image: "079.jpg"},
    {name: "Dude, Where's My Car?", rate: 5.5, image: "080.jpg"},
    {name: "Iron Man", rate: 7.9, image: "081.jpg"},
    {name: "Suicide Squad", rate: 6.2, image: "082.jpg"},
    {name: "The Fifth Element", rate: 7.7, image: "083.jpg"},
    {name: "12 Angry Men", rate: 8.9, image: "084.jpg"},
    {name: "City of God", rate: 8.7, image: "085.jpg"},
    {name: "Casino", rate: 8.2, image: "086.jpg"},
    {name: "Knockin' on Heaven's Door", rate: 8.0, image: "087.jpg"},
    {name: "The Green Mile", rate: 8.5, image: "088.jpg"},
    {name: "The Chronicles of Riddick", rate: 6.7, image: "089.jpg"},
    {name: "Riddick", rate: 6.4, image: "090.jpg"},
    {name: "Hellboy", rate: 6.8, image: "091.jpg"},
    {name: "Braveheart", rate: 8.4, image: "092.jpg"},
    {name: "RED", rate: 7.1, image: "093.jpg"},
    {name: "RED 2", rate: 6.7, image: "094.jpg"},
    {name: "Cloud Atlas", rate: 7.5, image: "095.jpg"},
    {name: "Interstellar", rate: 8.6, image: "096.jpg"},
    {name: "The Wolf of Wall Street", rate: 8.2, image: "097.jpg"},
    {name: "Home Alone", rate: 7.5, image: "098.jpg"},
    {name: "The Silence of the Lambs", rate: 8.6, image: "099.jpg"},
    {name: "1408", rate: 6.8, image: "100.jpg"},
    {name: "Don't Be a Menace to South Central While Drinking Your Juice in the Hood", rate: 6.6, image: "101.jpg"},
    {name: "Limitless", rate: 7.4, image: "102.jpg"},
    {name: "The Matrix", rate: 8.7, image: "103.jpg"},
    {name: "The Matrix Reloaded", rate: 7.2, image: "104.jpg"},
    {name: "The Matrix Revolutions", rate: 6.7, image: "105.jpg"},
    {name: "V for Vendetta", rate: 8.2, image: "106.jpg"},
    {name: "Dallas Buyers Club", rate: 8.0, image: "107.jpg"},
    {name: "Blow", rate: 7.6, image: "108.jpg"},
    {name: "Fight Club", rate: 8.8, image: "109.jpg"},
    {name: "Training Day", rate: 7.7, image: "110.jpg"},
    {name: "The Illusionist", rate: 7.6, image: "111.jpg"},
    {name: "The Fugitive", rate: 7.8, image: "112.jpg"},
    {name: "The Jewel of the Nile", rate: 6.1, image: "113.jpg"},
    {name: "The Curious Case of Benjamin Button", rate: 7.8, image: "114.jpg"},
    {name: "Bandits", rate: 6.5, image: "115.jpg"},
    {name: "The Usual Suspects", rate: 8.6, image: "116.jpg"},
    {name: "Around the World in 80 Days", rate: 5.8, image: "117.jpg"},
    {name: "There's Something About Mary", rate: 7.1, image: "118.jpg"},
    {name: "Edward Scissorhands", rate: 7.9, image: "119.jpg"},
    {name: "Mr. Nobody", rate: 7.9, image: "120.jpg"},
    {name: "A Midsummer Night's Dream", rate: 6.5, image: "121.jpg"},
    {name: "State of Play", rate: 7.1, image: "122.jpg"},
    {name: "Gladiator", rate: 8.5, image: "123.jpg"},
    {name: "Unknown", rate: 6.9, image: "124.jpg"},
    {name: "The Longest Yard", rate: 6.4, image: "125.jpg"},
    {name: "An Adventure in Space and Time", rate: 8.3, image: "126.jpg"},
    {name: "Back to the Future Part II", rate: 7.8, image: "127.jpg"},
    {name: "Back to the Future Part III", rate: 7.4, image: "128.jpg"},
    {name: "Guardians of the Galaxy", rate: 8.1, image: "129.jpg"},
    {name: "Guardians of the Galaxy Vol. 2", rate: 7.8, image: "130.jpg"},
    {name: "Bram Stoker's Dracula", rate: 7.5, image: "131.jpg"},
    {name: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe", rate: 6.9, image: "132.jpg"},
    {name: "Three Days of the Condor", rate: 7.5, image: "133.jpg"},
    {name: "RocknRolla", rate: 7.3, image: "134.jpg"},
    {name: "10 Things I Hate About You", rate: 7.2, image: "135.jpg"},
    {name: "Trainspotting", rate: 8.2, image: "136.jpg"},
    {name: "Le mac", rate: 6.1, image: "137.jpg"},
    {name: "The Godfather", rate: 9.2, image: "138.jpg"},
    {name: "The Hangover", rate: 7.8, image: "139.jpg"},
    {name: "No Country for Old Men", rate: 8.1, image: "140.jpg"},
    {name: "Schindler's List", rate: 8.9, image: "141.jpg"},
    {name: "The Big Lebowski", rate: 8.2, image: "142.jpg"},
    {name: "The Bucket List", rate: 7.4, image: "143.jpg"},
    {name: "The Devil's Advocate", rate: 7.5, image: "144.jpg"},
    {name: "The Sorcerer's Apprentice", rate: 6.1, image: "145.jpg"},
    {name: "In Bruges", rate: 7.9, image: "146.jpg"},
    {name: "In Time", rate: 6.7, image: "147.jpg"},
    {name: "District B13", rate: 7.2, image: "148.jpg"},
    {name: "Wasabi", rate: 6.6, image: "149.jpg"},
    {name: "Maleficent", rate: 7.0, image: "150.jpg"},
    {name: "Predestination", rate: 7.5, image: "151.jpg"},
    {name: "One Flew Over the Cuckoo's Nest", rate: 8.7, image: "152.jpg"},
    {name: "Timecop", rate: 5.8, image: "153.jpg"},
    {name: "The Prestige", rate: 8.5, image: "154.jpg"},
    {name: "From Dusk Till Dawn", rate: 7.3, image: "155.jpg"},
    {name: "Star Wars: Episode I - The Phantom Menace", rate: 6.5, image: "156.jpg"},
    {name: "Crank", rate: 7.0, image: "157.jpg"},
    {name: "Saving Private Ryan", rate: 8.6, image: "158.jpg"},
    {name: "Tropic Thunder", rate: 7.0, image: "159.jpg"},
    {name: "The Hangover Part II", rate: 6.5, image: "160.jpg"},
    {name: "The Hangover Part III", rate: 5.9, image: "161.jpg"},
    {name: "Burn After Reading", rate: 7.0, image: "162.jpg"},
    {name: "Sherlock Holmes", rate: 7.6, image: "163.jpg"},
    {name: "Léon: The Professional", rate: 8.6, image: "164.jpg"},
    {name: "The Thirteenth Floor", rate: 7.0, image: "165.jpg"},
    {name: "Waterworld", rate: 6.1, image: "166.jpg"},
    {name: "The Untouchables", rate: 7.9, image: "167.jpg"},
    {name: "Winged Migration", rate: 8.0, image: "168.jpg"},
    {name: "Hansel & Gretel: Witch Hunters", rate: 6.1, image: "169.jpg"},
    {name: "Gangs of New York", rate: 7.5, image: "170.jpg"},
    {name: "Wag the Dog", rate: 7.1, image: "171.jpg"},
    {name: "Unleashed", rate: 7.0, image: "172.jpg"},
    {name: "A Series of Unfortunate Events", rate: 6.8, image: "173.jpg"},
    {name: "Winter's Tale", rate: 6.2, image: "174.jpg"},
    {name: "Pirates of the Caribbean: The Curse of the Black Pearl", rate: 8.0, image: "175.jpg"},
    {name: "Pirates of the Caribbean: Dead Man's Chest", rate: 7.3, image: "176.jpg"},
    {name: "Pirates of the Caribbean: At World's End", rate: 7.1, image: "177.jpg"},
    {name: "Pirates of the Caribbean: On Stranger Tides", rate: 6.6, image: "178.jpg"},
    {name: "Pirates of the Caribbean: Dead Men Tell No Tales", rate: 6.8, image: "179.jpg"},
    {name: "At Eternitys Gate", rate: 6.9, image: "180.jpg"},
    {name: "Glass", rate: 6.7, image: "181.jpg"},
    {name: "The Upside", rate: 6.8, image: "182.jpg"},
    {name: "Mary Queen of Scots", rate: 6.3, image: "183.jpg"},
    {name: "Green book", rate: 8.2, image: "184.jpg"},
    {name: "The Favourite", rate: 7.6, image: "185.jpg"},
    {name: "Welcome Home", rate: 5.6, image: "186.jpg"},
    {name: "Madonna and the Breakfast Club", rate: 6.6, image: "187.jpg"},
    {name: "Captain Marvel", rate: 6.9, image: "188.jpg"},
    {name: "Ben is Back", rate: 6.7, image: "189.jpg"},
    {name: "Mia et le lion blanc", rate: 6.5, image: "190.jpg"},
    {name: "Dumbo", rate: 6.3, image: "191.jpg"},
    {name: "Shazam!", rate: 7.1, image: "192.jpg"},
    ];